CREATE TABLE `listas_binnacle` (
	`id` INT(255) NOT NULL AUTO_INCREMENT,
	`id_usuario` INT(100) NOT NULL,
	`ip` VARCHAR(50) NULL DEFAULT NULL,
	`seccion` VARCHAR(50) NULL DEFAULT NULL,
	`date` DATETIME NULL DEFAULT NULL,
	`accion` VARCHAR(100) NULL DEFAULT NULL,
	`detalles` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
